version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /home/circleci/gommit
    environment:
       BASH_ENV: /home/circleci/.bashrc
    steps:
      - checkout
      - run:
          name: Install gometalinter
          command: |
            export GO111MODULE=off
            go get github.com/alecthomas/gometalinter
            gometalinter --install --update
      - run:
          name: Install vendors
          command: |
            export GO111MODULE=on
            go mod vendor
      - run:
          name: Run tests
          command: |
            make test-all
      - run:
          name: Push on codecov result
          command: |
            bash <(curl -s https://codecov.io/bash)
